resilience4j:
  circuitbreaker:
    configs: 
      default-config: # We set the name for this config
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4 # number of ok requests to be redimish
    instances:
      OauthCircuitBreaker:  # The name we set in the code in OauthController.java from CircuitBreakerFactory bean.
        base-config: default-config # name already set before
  timelimiter:
    configs:
      default-config:
        timeout-duration: 3s
    instances:
      OauthCircuitBreaker:
        base-config: default-config
